services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=trashboard;Username=postgres;Password=postgres
    depends_on:
    - db
    ports:
      - "8080:8080"

  web:
    build:
      context: ./frontend/angular-app
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "4200:80"

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trashboard
    ports:
      - "5433:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: