services:
  api:
    build:
      context: ./backend/TrashBoard.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"

  web:
    build:
      context: ./frontend/angular-app
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "4200:80"

